### PR TITLE
Ling's Unsupervised Learning Assignment

### PR DESCRIPTION
**Pull request by Papadogs**

### CODE REVIEW

**Comment by bensoltoff** [comment]
You have files in the main directory. Move everything into your `student` folder in order to merge the PR

**Comment by Papadogs** [comment]
Sorry for the inconvenience. I have now put the files into the student folder and pushed the files.

**Comment by bensoltoff** [comment]
You still have a `Unsupervised_Learning_files` folder in the top directory. Move this to your student folder so I can merge the PR

**Comment by Papadogs** [comment]
Sorry. I had two finals this afternoon and did not notice the reply. I believe the files are in the correct folder now.
Thank you for patience!

**Pull request merged**
