### PR TITLE
Assignment2-Siyi Fan

### PR DESCRIPTION
**Pull request by siyiii**

### CODE REVIEW

**Comment by rchughes** [comment]
Hi Siyi,

Please review the assignment submission instructions and update your pull request. Specifically, your homework should be in folder

students/fan_siyi/FILENAME

not in the general "assignments" folder.

Thanks,
Ryan

**Comment by rchughes** [comment]
Hi Siyi,

You still need to delete your modification of "assignment 2" from the assignments/ folder.

Thanks,
Ryan

**Comment by rchughes** [comment]
Hi Siyi,

I'm still seeing the modified Assignment 2 in your assignments folder. I'd consider backing up your work and following Josh's instructions for force syncing your fork. 

Thanks,
Ryan

**Comment by jmausolf** [comment]
Hi Siyi,

I see the file in your students folder, but you have many discrepant commits to the assignments folder. I would second recommending backing up your Assignment 2, force-syncing, and then, adding the single Assignment 2 file to your student's folder.

Best,
Josh

**Pull request closed without merging**
